name: besca_dev
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - python=3.9
 - scipy>=1.5.4
 - flask-restful>=0.3.9
 - dominate>=2.6.0
 - requests>=2.26.0
 - numpy>=1.18.0
 - scanpy>=1.7.2
 - plotly>=5.4.0
 - anndata>=0.7.4
 - seaborn>=0.11.2
 - mygene>=3.2.2
 - pandas>=1.1.0
 - matplotlib>=3.5.0
 - bbknn>=1.5.1
 - nbclean>=0.3.2
 - python-igraph>=0.9.8
 - leidenalg>=0.8.3
 - scanorama>=1.7.1
 - scvelo>=0.2.4
 - umap-learn>=0.5.2
 - sinfo>=0.3.1
 - pydot>=1.4.2
 - scvi-tools>=0.14.3
 - ipython>=7.30.1
<<<<<<< HEAD
 - pytest
=======
 - git>=2.34.1
 - pytest>=7.1.2
>>>>>>> a12fc4acf6a7b8aba326495dd380e187171ccc99
 - pip
 - pip:
   - scikit_learn>=1.0.0
   - git+https://github.com/bedapub/besca.git
